#!/usr/bin/env Rscript

# Prepare manuscript-ready tables and figures comparing the predictive
# performance of GAM-DMR (MGCV), SOMNiBUS, DMRcate, and BSmooth across the
# same 100 repeated family-aware outer train/test splits.
#
# Required inputs are the collected outputs generated by the four primary
# prediction pipelines under results/15_revision/5_cv/5_prediction/.
#
# Main outputs:
#   - descriptive performance table across outer test splits;
#   - corrected repeated-CV pairwise comparisons;
#   - each regional method versus the covariate-only model;
#   - model-complexity and feature-selection summaries;
#   - subject-averaged ROC, PR, and calibration curves;
#   - manuscript-ready PDF and PNG figures;
#   - a text summary that can be adapted for the Results section.

suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
  library(pROC)
  library(PRROC)
})

data.table::setDTthreads(1L)
options(stringsAsFactors = FALSE)

# ------------------------------- configuration -------------------------------

PATH_wk <- path.expand(
  Sys.getenv("PATH_WK", "~/scratch/UQAC/meth/")
)

prediction_root <- file.path(
  PATH_wk,
  "results/15_revision/5_cv/5_prediction"
)

method_config <- data.table(
  method_key = c("MGCV", "SOMNiBUS", "DMRcate", "BSmooth"),
  method_display = c("GAM-DMR", "SOMNiBUS", "DMRcate", "BSmooth"),
  method_order = 1:4,
  primary_model = c(
    "MGCV_PC12_LASSO",
    "SOMNiBUS_PC12_LASSO",
    "DMRcate_PC12_LASSO",
    "BSmooth_PC12_LASSO"
  ),
  input_root = c(
    Sys.getenv(
      "MGCV_PREDICTION_OUTPUT",
      file.path(prediction_root, "1_mgcv_primary")
    ),
    Sys.getenv(
      "SOMNIBUS_PREDICTION_OUTPUT",
      file.path(prediction_root, "2_somnibus_primary")
    ),
    Sys.getenv(
      "DMRCATE_PREDICTION_OUTPUT",
      file.path(prediction_root, "3_dmrcate_primary")
    ),
    Sys.getenv(
      "BSMOOTH_PREDICTION_OUTPUT",
      file.path(prediction_root, "4_bsmooth_primary")
    )
  ),
  file_prefix = c("mgcv", "somnibus", "dmrcate", "bsmooth")
)

output_root <- path.expand(
  Sys.getenv(
    "REGIONAL_COMPARISON_OUTPUT",
    file.path(prediction_root, "5_regional_method_comparison")
  )
)

table_dir <- file.path(output_root, "tables")
figure_dir <- file.path(output_root, "figures")
data_dir <- file.path(output_root, "data")
qc_dir <- file.path(output_root, "qc")

expected_splits <- suppressWarnings(
  as.integer(Sys.getenv("EXPECTED_SPLITS", "100"))
)

overwrite <- Sys.getenv("OVERWRITE", "0") %in%
  c("1", "TRUE", "true", "T", "yes", "YES")

n_calibration_bins <- suppressWarnings(
  as.integer(Sys.getenv("N_CALIBRATION_BINS", "10"))
)

top_regions_per_method <- suppressWarnings(
  as.integer(Sys.getenv("TOP_REGIONS_PER_METHOD", "12"))
)

if (is.na(expected_splits) || expected_splits < 2L) {
  stop("EXPECTED_SPLITS must be at least 2.")
}

if (is.na(n_calibration_bins) || n_calibration_bins < 3L) {
  stop("N_CALIBRATION_BINS must be at least 3.")
}

if (is.na(top_regions_per_method) || top_regions_per_method < 1L) {
  stop("TOP_REGIONS_PER_METHOD must be positive.")
}

if (dir.exists(output_root)) {
  old_files <- list.files(output_root, recursive = TRUE, full.names = TRUE)

  if (length(old_files) > 0L && !overwrite) {
    stop(
      "Comparison output already exists. Set OVERWRITE=1 to replace it. ",
      "First existing file: ", old_files[1L]
    )
  }

  if (overwrite) {
    unlink(output_root, recursive = TRUE, force = TRUE)
  }
}

for (d in c(output_root, table_dir, figure_dir, data_dir, qc_dir)) {
  dir.create(d, recursive = TRUE, showWarnings = FALSE)
}

# ------------------------------ display settings -----------------------------

method_levels <- c(
  "GAM-DMR",
  "SOMNiBUS",
  "DMRcate",
  "BSmooth",
  "Covariates only"
)

method_palette <- c(
  "GAM-DMR" = "#0072B2",
  "SOMNiBUS" = "#D55E00",
  "DMRcate" = "#009E73",
  "BSmooth" = "#CC79A7",
  "Covariates only" = "#666666"
)

base_theme <- theme_bw(base_size = 12) +
  theme(
    panel.grid.minor = element_blank(),
    legend.position = "right",
    plot.title = element_text(face = "bold"),
    strip.background = element_rect(fill = "grey95"),
    strip.text = element_text(face = "bold")
  )

# -------------------------------- utilities ----------------------------------

repair_duplicate_column_names <- function(dt, file_path, label) {
  nm <- names(dt)

  if (!anyDuplicated(nm)) {
    return(dt)
  }

  # Compatibility with the first MGCV/SOMNiBUS output version, which could
  # contain both total test n and evaluable test n under the same name.
  n_test_idx <- which(nm == "n_test")

  if (length(n_test_idx) > 1L) {
    nm[n_test_idx[-1L]] <- paste0(
      "n_evaluable_test",
      if (length(n_test_idx) > 2L) {
        paste0("_", seq_len(length(n_test_idx) - 1L))
      } else {
        ""
      }
    )
  }

  if (anyDuplicated(nm)) {
    duplicate_names <- unique(
      nm[duplicated(nm) | duplicated(nm, fromLast = TRUE)]
    )

    stop(
      label,
      " still has duplicated column names after repair: ",
      basename(file_path),
      " [",
      paste(duplicate_names, collapse = ", "),
      "]"
    )
  }

  setnames(dt, nm)
  dt
}

read_required_table <- function(file_path, label) {
  if (!file.exists(file_path)) {
    stop(label, " does not exist: ", file_path)
  }

  dt <- fread(file_path, showProgress = FALSE)
  repair_duplicate_column_names(dt, file_path, label)
}

require_columns <- function(dt, columns, label) {
  missing_columns <- setdiff(columns, names(dt))

  if (length(missing_columns) > 0L) {
    stop(
      label,
      " is missing columns: ",
      paste(missing_columns, collapse = ", ")
    )
  }
}

as_logical_safe <- function(x) {
  if (is.logical(x)) return(x)

  as.character(x) %in% c(
    "1", "TRUE", "true", "T", "yes", "YES"
  )
}

safe_mean <- function(x) {
  x <- as.numeric(x)
  x <- x[is.finite(x)]
  if (length(x) == 0L) NA_real_ else mean(x)
}

safe_sd <- function(x) {
  x <- as.numeric(x)
  x <- x[is.finite(x)]
  if (length(x) < 2L) NA_real_ else stats::sd(x)
}

safe_quantile <- function(x, p) {
  x <- as.numeric(x)
  x <- x[is.finite(x)]
  if (length(x) == 0L) NA_real_ else as.numeric(
    stats::quantile(x, p, names = FALSE, type = 7)
  )
}

safe_roc_auc <- function(y, p) {
  y <- as.integer(y)
  p <- as.numeric(p)
  keep <- is.finite(y) & is.finite(p)
  y <- y[keep]
  p <- p[keep]

  if (length(y) < 2L || length(unique(y)) < 2L) {
    return(NA_real_)
  }

  obj <- tryCatch(
    pROC::roc(
      response = y,
      predictor = p,
      levels = c(0, 1),
      direction = "<",
      quiet = TRUE
    ),
    error = function(e) NULL
  )

  if (is.null(obj)) NA_real_ else as.numeric(pROC::auc(obj))
}

safe_pr_auc <- function(y, p) {
  y <- as.integer(y)
  p <- as.numeric(p)
  keep <- is.finite(y) & is.finite(p)
  y <- y[keep]
  p <- p[keep]

  if (length(y) < 2L || length(unique(y)) < 2L) {
    return(NA_real_)
  }

  obj <- tryCatch(
    PRROC::pr.curve(
      scores.class0 = p[y == 1L],
      scores.class1 = p[y == 0L],
      curve = FALSE
    ),
    error = function(e) NULL
  )

  if (is.null(obj)) NA_real_ else as.numeric(obj$auc.integral)
}

probability_metrics <- function(y, p) {
  y <- as.integer(y)
  p <- as.numeric(p)
  keep <- is.finite(y) & is.finite(p)
  y <- y[keep]
  p <- p[keep]

  if (length(y) == 0L) {
    return(
      data.table(
        n_subjects = 0L,
        n_cases = 0L,
        n_controls = 0L,
        prevalence = NA_real_,
        AUROC = NA_real_,
        PR_AUC = NA_real_,
        PR_AUC_lift = NA_real_,
        Brier = NA_real_,
        log_loss = NA_real_,
        calibration_intercept = NA_real_,
        calibration_slope = NA_real_
      )
    )
  }

  p_clip <- pmin(pmax(p, 1e-8), 1 - 1e-8)
  lp <- qlogis(p_clip)
  calibration_intercept <- NA_real_
  calibration_slope <- NA_real_

  if (
    length(unique(y)) >= 2L &&
      is.finite(stats::sd(lp)) &&
      stats::sd(lp) > 0
  ) {
    intercept_fit <- tryCatch(
      suppressWarnings(
        stats::glm(
          y ~ 1 + offset(lp),
          family = stats::binomial()
        )
      ),
      error = function(e) NULL
    )

    slope_fit <- tryCatch(
      suppressWarnings(
        stats::glm(
          y ~ lp,
          family = stats::binomial()
        )
      ),
      error = function(e) NULL
    )

    if (!is.null(intercept_fit)) {
      calibration_intercept <- unname(coef(intercept_fit)[1L])
    }

    if (!is.null(slope_fit) && length(coef(slope_fit)) >= 2L) {
      calibration_slope <- unname(coef(slope_fit)[2L])
    }
  }

  prevalence <- mean(y)
  pr_auc <- safe_pr_auc(y, p)

  data.table(
    n_subjects = length(y),
    n_cases = sum(y == 1L),
    n_controls = sum(y == 0L),
    prevalence = prevalence,
    AUROC = safe_roc_auc(y, p),
    PR_AUC = pr_auc,
    PR_AUC_lift = pr_auc - prevalence,
    Brier = mean((p - y)^2),
    log_loss = -mean(
      y * log(p_clip) + (1 - y) * log(1 - p_clip)
    ),
    calibration_intercept = calibration_intercept,
    calibration_slope = calibration_slope
  )
}

corrected_repeated_cv <- function(difference, test_train_ratio) {
  d <- as.numeric(difference)
  ratio <- as.numeric(test_train_ratio)
  keep <- is.finite(d) & is.finite(ratio)
  d <- d[keep]
  ratio <- ratio[keep]
  n <- length(d)

  if (n < 3L) {
    return(
      data.table(
        n_splits = n,
        mean_difference = if (n > 0L) mean(d) else NA_real_,
        median_difference = if (n > 0L) median(d) else NA_real_,
        corrected_SE = NA_real_,
        corrected_CI_low = NA_real_,
        corrected_CI_high = NA_real_,
        corrected_t = NA_real_,
        corrected_df = if (n > 0L) n - 1L else NA_integer_,
        corrected_pvalue = NA_real_,
        mean_test_train_ratio = if (n > 0L) mean(ratio) else NA_real_
      )
    )
  }

  mean_d <- mean(d)
  variance_d <- stats::var(d)
  ratio_mean <- mean(ratio)
  corrected_se <- sqrt((1 / n + ratio_mean) * variance_d)
  df <- n - 1L

  if (!is.finite(corrected_se) || corrected_se == 0) {
    t_value <- NA_real_
    p_value <- NA_real_
    ci_low <- mean_d
    ci_high <- mean_d
  } else {
    t_value <- mean_d / corrected_se
    p_value <- 2 * stats::pt(-abs(t_value), df = df)
    critical <- stats::qt(0.975, df = df)
    ci_low <- mean_d - critical * corrected_se
    ci_high <- mean_d + critical * corrected_se
  }

  data.table(
    n_splits = n,
    mean_difference = mean_d,
    median_difference = median(d),
    corrected_SE = corrected_se,
    corrected_CI_low = ci_low,
    corrected_CI_high = ci_high,
    corrected_t = t_value,
    corrected_df = df,
    corrected_pvalue = p_value,
    mean_test_train_ratio = ratio_mean
  )
}

format_number <- function(x, digits = 3L) {
  ifelse(
    is.finite(x),
    formatC(x, digits = digits, format = "f"),
    "NA"
  )
}

format_pvalue <- function(x) {
  ifelse(
    !is.finite(x),
    "NA",
    ifelse(x < 0.001, "<0.001", formatC(x, digits = 3, format = "f"))
  )
}

save_plot <- function(plot_object, filename_stub, width, height) {
  ggsave(
    filename = file.path(figure_dir, paste0(filename_stub, ".pdf")),
    plot = plot_object,
    width = width,
    height = height,
    units = "in"
  )

  ggsave(
    filename = file.path(figure_dir, paste0(filename_stub, ".png")),
    plot = plot_object,
    width = width,
    height = height,
    units = "in",
    dpi = 400
  )
}

# ------------------------------- input loading -------------------------------

performance_list <- list()
prediction_list <- list()
coefficient_list <- list()
split_qc_list <- list()

for (i in seq_len(nrow(method_config))) {
  cfg <- method_config[i]
  collected_dir <- file.path(cfg$input_root, "collected")

  performance_file <- file.path(
    collected_dir,
    paste0(cfg$file_prefix, "_primary_performance_all_splits.tsv")
  )

  prediction_file <- file.path(
    collected_dir,
    paste0(cfg$file_prefix, "_primary_predictions_all_splits.tsv")
  )

  coefficient_file <- file.path(
    collected_dir,
    paste0(cfg$file_prefix, "_primary_coefficients_all_splits.tsv")
  )

  split_qc_file <- file.path(
    collected_dir,
    paste0(cfg$file_prefix, "_primary_split_qc_all_splits.tsv")
  )

  perf <- read_required_table(
    performance_file,
    paste0(cfg$method_display, " performance table")
  )

  pred <- read_required_table(
    prediction_file,
    paste0(cfg$method_display, " prediction table")
  )

  coef_dt <- read_required_table(
    coefficient_file,
    paste0(cfg$method_display, " coefficient table")
  )

  split_qc <- read_required_table(
    split_qc_file,
    paste0(cfg$method_display, " split-QC table")
  )

  require_columns(
    perf,
    c(
      "splitID", "model", "n_train", "n_test",
      "AUROC_test", "PR_AUC_test", "PR_AUC_lift_test", "Brier_test",
      "log_loss_test", "calibration_intercept_test",
      "calibration_slope_test", "sensitivity_test",
      "specificity_test", "balanced_accuracy_test",
      "n_DMR_selected_input", "n_DMR_usable",
      "n_methylation_features_input",
      "n_methylation_features_nonzero",
      "n_features_nonzero",
      "model_fallback"
    ),
    paste0(cfg$method_display, " performance table")
  )

  require_columns(
    pred,
    c(
      "splitID", "model", "ID", "FID", "AA_only",
      "prediction_set", "pred_prob"
    ),
    paste0(cfg$method_display, " prediction table")
  )

  require_columns(
    coef_dt,
    c(
      "splitID", "model", "feature", "feature_type",
      "coefficient", "selected_nonzero"
    ),
    paste0(cfg$method_display, " coefficient table")
  )

  require_columns(
    split_qc,
    c("splitID", "n_train", "n_test"),
    paste0(cfg$method_display, " split-QC table")
  )

  perf[, `:=`(
    source_method = cfg$method_key,
    method_display = cfg$method_display,
    primary_model_expected = cfg$primary_model,
    splitID = as.integer(splitID),
    model_fallback = as_logical_safe(model_fallback)
  )]

  pred[, `:=`(
    source_method = cfg$method_key,
    method_display = cfg$method_display,
    primary_model_expected = cfg$primary_model,
    splitID = as.integer(splitID),
    ID = as.character(ID),
    FID = as.character(FID),
    AA_only = as.integer(AA_only),
    pred_prob = as.numeric(pred_prob)
  )]

  coef_dt[, `:=`(
    source_method = cfg$method_key,
    method_display = cfg$method_display,
    primary_model_expected = cfg$primary_model,
    splitID = as.integer(splitID),
    selected_nonzero = as.integer(selected_nonzero)
  )]

  split_qc[, `:=`(
    source_method = cfg$method_key,
    method_display = cfg$method_display,
    splitID = as.integer(splitID)
  )]

  primary_count <- perf[model == cfg$primary_model, uniqueN(splitID)]
  baseline_count <- perf[model == "Covariate_only", uniqueN(splitID)]

  if (primary_count != expected_splits) {
    stop(
      cfg$method_display,
      " has ", primary_count,
      " primary-model splits; expected ", expected_splits, "."
    )
  }

  if (baseline_count != expected_splits) {
    stop(
      cfg$method_display,
      " has ", baseline_count,
      " covariate-only splits; expected ", expected_splits, "."
    )
  }

  performance_list[[cfg$method_key]] <- perf
  prediction_list[[cfg$method_key]] <- pred
  coefficient_list[[cfg$method_key]] <- coef_dt
  split_qc_list[[cfg$method_key]] <- split_qc

  cat(
    "Loaded ", cfg$method_display,
    ": performance rows=", nrow(perf),
    ", prediction rows=", nrow(pred),
    ", coefficient rows=", nrow(coef_dt),
    "\n",
    sep = ""
  )
}

performance_all <- rbindlist(
  performance_list,
  use.names = TRUE,
  fill = TRUE
)

prediction_all <- rbindlist(
  prediction_list,
  use.names = TRUE,
  fill = TRUE
)

coefficient_all <- rbindlist(
  coefficient_list,
  use.names = TRUE,
  fill = TRUE
)

split_qc_all <- rbindlist(
  split_qc_list,
  use.names = TRUE,
  fill = TRUE
)

# Derived calibration-error metrics are easier to compare because lower is
# unambiguously better.
performance_all[, calibration_intercept_abs_test := abs(
  calibration_intercept_test
)]
performance_all[, calibration_slope_error_test := abs(
  calibration_slope_test - 1
)]

primary_performance <- performance_all[
  model == primary_model_expected
]

baseline_performance_all <- performance_all[
  model == "Covariate_only"
]

setorder(primary_performance, source_method, splitID)
setorder(baseline_performance_all, source_method, splitID)

# ------------------------- baseline consistency checks -----------------------

baseline_metrics_for_qc <- c(
  "AUROC_test",
  "PR_AUC_test",
  "Brier_test",
  "log_loss_test",
  "calibration_intercept_test",
  "calibration_slope_test",
  "sensitivity_test",
  "specificity_test",
  "balanced_accuracy_test"
)

baseline_metric_qc <- rbindlist(
  lapply(
    baseline_metrics_for_qc,
    function(metric) {
      baseline_performance_all[
        ,
        {
          z <- as.numeric(get(metric))
          z <- z[is.finite(z)]

          list(
            n_methods = .N,
            minimum = if (length(z)) min(z) else NA_real_,
            maximum = if (length(z)) max(z) else NA_real_,
            range = if (length(z)) max(z) - min(z) else NA_real_
          )
        },
        by = splitID
      ][
        ,
        .(
          metric = metric,
          n_splits_checked = .N,
          maximum_cross_method_range = max(range, na.rm = TRUE),
          mean_cross_method_range = mean(range, na.rm = TRUE)
        )
      ]
    }
  ),
  use.names = TRUE,
  fill = TRUE
)

fwrite(
  baseline_metric_qc,
  file.path(qc_dir, "QC_covariate_performance_consistency.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

baseline_prediction_qc_list <- list()
reference_baseline_prediction <- prediction_all[
  source_method == "MGCV" &
    model == "Covariate_only" &
    prediction_set == "test",
  .(
    splitID,
    ID,
    FID,
    AA_only_reference = AA_only,
    pred_prob_reference = pred_prob
  )
]

if (nrow(reference_baseline_prediction) == 0L) {
  stop("MGCV covariate-only test predictions are unavailable.")
}

for (method_key in method_config$method_key) {
  current_method_key <- method_key

  candidate <- prediction_all[
    source_method == method_key &
      model == "Covariate_only" &
      prediction_set == "test",
    .(
      splitID,
      ID,
      FID,
      AA_only_candidate = AA_only,
      pred_prob_candidate = pred_prob
    )
  ]

  merged_baseline <- merge(
    reference_baseline_prediction,
    candidate,
    by = c("splitID", "ID", "FID"),
    all = TRUE
  )

  baseline_prediction_qc_list[[method_key]] <- data.table(
    source_method = method_key,
    method_display = method_config[
      method_key == current_method_key,
      method_display
    ][1L],
    n_reference_rows = nrow(reference_baseline_prediction),
    n_candidate_rows = nrow(candidate),
    n_matched_rows = merged_baseline[
      !is.na(pred_prob_reference) & !is.na(pred_prob_candidate),
      .N
    ],
    n_outcome_mismatches = merged_baseline[
      !is.na(AA_only_reference) &
        !is.na(AA_only_candidate) &
        AA_only_reference != AA_only_candidate,
      .N
    ],
    mean_abs_prediction_difference = merged_baseline[
      ,
      mean(
        abs(pred_prob_reference - pred_prob_candidate),
        na.rm = TRUE
      )
    ],
    max_abs_prediction_difference = merged_baseline[
      ,
      max(
        abs(pred_prob_reference - pred_prob_candidate),
        na.rm = TRUE
      )
    ]
  )
}

baseline_prediction_qc <- rbindlist(
  baseline_prediction_qc_list,
  use.names = TRUE,
  fill = TRUE
)

fwrite(
  baseline_prediction_qc,
  file.path(qc_dir, "QC_covariate_prediction_consistency.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

max_baseline_prediction_difference <- max(
  baseline_prediction_qc$max_abs_prediction_difference,
  na.rm = TRUE
)

if (
  is.finite(max_baseline_prediction_difference) &&
    max_baseline_prediction_difference > 1e-8
) {
  warning(
    "Covariate-only predictions differ across method pipelines. ",
    "See QC_covariate_prediction_consistency.tsv. Maximum difference: ",
    signif(max_baseline_prediction_difference, 6)
  )
}

# Use the MGCV covariate-only result once in cross-method descriptive tables.
baseline_reference_performance <- baseline_performance_all[
  source_method == "MGCV"
]
baseline_reference_performance[, method_display := "Covariates only"]
baseline_reference_performance[, source_method := "Covariate_only"]

performance_for_summary <- rbindlist(
  list(primary_performance, baseline_reference_performance),
  use.names = TRUE,
  fill = TRUE
)

performance_for_summary[, method_display := factor(
  method_display,
  levels = method_levels
)]

# Save standardized combined analysis datasets.
fwrite(
  primary_performance,
  file.path(data_dir, "primary_performance_4_methods_all_splits.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

fwrite(
  performance_for_summary,
  file.path(data_dir, "performance_4_methods_plus_covariates_all_splits.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

# ------------------------ Table 1: performance summary -----------------------

performance_metric_dictionary <- data.table(
  metric = c(
    "AUROC_test",
    "PR_AUC_test",
    "PR_AUC_lift_test",
    "Brier_test",
    "log_loss_test",
    "calibration_intercept_test",
    "calibration_slope_test",
    "sensitivity_test",
    "specificity_test",
    "balanced_accuracy_test"
  ),
  metric_display = c(
    "AUROC",
    "PR-AUC",
    "PR-AUC lift",
    "Brier score",
    "Log loss",
    "Calibration intercept",
    "Calibration slope",
    "Sensitivity",
    "Specificity",
    "Balanced accuracy"
  ),
  digits = c(3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L)
)

performance_long <- melt(
  performance_for_summary,
  id.vars = c("splitID", "source_method", "method_display"),
  measure.vars = performance_metric_dictionary$metric,
  variable.name = "metric",
  value.name = "value",
  variable.factor = FALSE
)

performance_long <- merge(
  performance_long,
  performance_metric_dictionary,
  by = "metric",
  all.x = TRUE,
  sort = FALSE
)

performance_summary_numeric <- performance_long[
  ,
  .(
    n_splits = sum(is.finite(value)),
    mean = safe_mean(value),
    SD = safe_sd(value),
    median = safe_quantile(value, 0.50),
    Q1 = safe_quantile(value, 0.25),
    Q3 = safe_quantile(value, 0.75),
    percentile_2_5 = safe_quantile(value, 0.025),
    percentile_97_5 = safe_quantile(value, 0.975)
  ),
  by = .(
    source_method,
    method_display,
    metric,
    metric_display,
    digits
  )
]

performance_summary_numeric[, method_order := match(
  as.character(method_display),
  method_levels
)]
setorder(performance_summary_numeric, method_order, metric_display)

fwrite(
  performance_summary_numeric,
  file.path(table_dir, "Table1_primary_performance_numeric_long.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

performance_summary_numeric[, formatted := paste0(
  format_number(mean, 3L),
  " (",
  format_number(SD, 3L),
  "); ",
  format_number(median, 3L),
  " [",
  format_number(Q1, 3L),
  ", ",
  format_number(Q3, 3L),
  "]"
)]

performance_summary_formatted <- dcast(
  performance_summary_numeric,
  method_display + method_order ~ metric_display,
  value.var = "formatted"
)
setorder(performance_summary_formatted, method_order)
performance_summary_formatted[, method_order := NULL]
setnames(performance_summary_formatted, "method_display", "Method")

fwrite(
  performance_summary_formatted,
  file.path(table_dir, "Table1_primary_performance_formatted.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

# --------------------- Table S3: model-complexity summary --------------------

complexity_metrics <- data.table(
  metric = c(
    "n_DMR_selected_input",
    "n_DMR_usable",
    "n_methylation_features_input",
    "n_methylation_features_nonzero",
    "n_features_nonzero"
  ),
  metric_display = c(
    "Selected DMRs",
    "Usable DMRs",
    "Input methylation PC features",
    "Nonzero methylation PC features",
    "All nonzero model features"
  )
)

complexity_long <- melt(
  primary_performance,
  id.vars = c(
    "splitID", "source_method", "method_display", "model_fallback"
  ),
  measure.vars = complexity_metrics$metric,
  variable.name = "metric",
  value.name = "value",
  variable.factor = FALSE
)

complexity_long <- merge(
  complexity_long,
  complexity_metrics,
  by = "metric",
  all.x = TRUE,
  sort = FALSE
)

complexity_summary <- complexity_long[
  ,
  .(
    n_splits = sum(is.finite(value)),
    mean = safe_mean(value),
    SD = safe_sd(value),
    median = safe_quantile(value, 0.50),
    Q1 = safe_quantile(value, 0.25),
    Q3 = safe_quantile(value, 0.75),
    minimum = if (any(is.finite(value))) min(value, na.rm = TRUE) else NA_real_,
    maximum = if (any(is.finite(value))) max(value, na.rm = TRUE) else NA_real_
  ),
  by = .(
    source_method,
    method_display,
    metric,
    metric_display
  )
]

additional_complexity <- primary_performance[
  ,
  .(
    n_splits = .N,
    fallback_splits = sum(model_fallback, na.rm = TRUE),
    fallback_rate = mean(model_fallback, na.rm = TRUE),
    splits_with_nonzero_methylation = sum(
      n_methylation_features_nonzero > 0,
      na.rm = TRUE
    ),
    proportion_with_nonzero_methylation = mean(
      n_methylation_features_nonzero > 0,
      na.rm = TRUE
    )
  ),
  by = .(
    source_method,
    method_display
  )
]

fwrite(
  complexity_summary,
  file.path(table_dir, "Table_S3_model_complexity_numeric_long.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

fwrite(
  additional_complexity,
  file.path(table_dir, "Table_S3_model_fallback_and_selection_rates.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

complexity_summary[, formatted := paste0(
  format_number(median, 1L),
  " [",
  format_number(Q1, 1L),
  ", ",
  format_number(Q3, 1L),
  "]"
)]

complexity_formatted <- dcast(
  complexity_summary,
  source_method + method_display ~ metric_display,
  value.var = "formatted"
)

complexity_formatted <- merge(
  complexity_formatted,
  additional_complexity,
  by = c("source_method", "method_display"),
  all.x = TRUE
)

complexity_formatted[, method_order := match(
  method_display,
  method_config$method_display
)]
setorder(complexity_formatted, method_order)
complexity_formatted[, method_order := NULL]

fwrite(
  complexity_formatted,
  file.path(table_dir, "Table_S3_model_complexity_formatted.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

# -------------------- corrected pairwise method comparison -------------------

comparison_metric_dictionary <- data.table(
  metric = c(
    "AUROC_test",
    "PR_AUC_test",
    "Brier_test",
    "log_loss_test",
    "calibration_intercept_abs_test",
    "calibration_slope_error_test",
    "balanced_accuracy_test"
  ),
  metric_display = c(
    "AUROC",
    "PR-AUC",
    "Brier score",
    "Log loss",
    "Absolute calibration intercept",
    "Absolute calibration-slope error",
    "Balanced accuracy"
  ),
  lower_is_better = c(FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE),
  main_manuscript_metric = c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE)
)

method_pairs <- combn(
  method_config$method_key,
  2L,
  simplify = FALSE
)

pairwise_results_list <- list()
pairwise_split_differences_list <- list()
result_index <- 0L
split_index <- 0L

for (pair in method_pairs) {
  method_a <- pair[1L]
  method_b <- pair[2L]

  display_a <- method_config[method_key == method_a, method_display][1L]
  display_b <- method_config[method_key == method_b, method_display][1L]

  perf_a <- primary_performance[
    source_method == method_a
  ]
  perf_b <- primary_performance[
    source_method == method_b
  ]

  paired <- merge(
    perf_a,
    perf_b,
    by = "splitID",
    suffixes = c("_A", "_B"),
    all = FALSE
  )

  if (nrow(paired) != expected_splits) {
    stop(
      "Pair ", display_a, " versus ", display_b,
      " has ", nrow(paired), " matched splits; expected ",
      expected_splits, "."
    )
  }

  paired[, test_train_ratio := (
    n_test_A / n_train_A + n_test_B / n_train_B
  ) / 2]

  for (m in seq_len(nrow(comparison_metric_dictionary))) {
    metric <- comparison_metric_dictionary$metric[m]
    metric_display <- comparison_metric_dictionary$metric_display[m]
    lower_is_better <- comparison_metric_dictionary$lower_is_better[m]

    raw_difference <- paired[[paste0(metric, "_A")]] -
      paired[[paste0(metric, "_B")]]

    favorable_sign <- if (lower_is_better) -1 else 1
    favorable_difference <- favorable_sign * raw_difference

    corrected <- corrected_repeated_cv(
      raw_difference,
      paired$test_train_ratio
    )

    corrected[, `:=`(
      method_A = method_a,
      method_B = method_b,
      method_A_display = display_a,
      method_B_display = display_b,
      comparison = paste0(display_a, " minus ", display_b),
      metric = metric,
      metric_display = metric_display,
      lower_is_better = lower_is_better,
      favorable_sign = favorable_sign,
      favorable_mean_difference = favorable_sign * mean_difference,
      favorable_CI_low = if (favorable_sign == 1) {
        corrected_CI_low
      } else {
        -corrected_CI_high
      },
      favorable_CI_high = if (favorable_sign == 1) {
        corrected_CI_high
      } else {
        -corrected_CI_low
      },
      win_rate_method_A = mean(
        favorable_difference > 0,
        na.rm = TRUE
      ),
      tie_rate = mean(
        favorable_difference == 0,
        na.rm = TRUE
      )
    )]

    result_index <- result_index + 1L
    pairwise_results_list[[result_index]] <- corrected

    split_index <- split_index + 1L
    pairwise_split_differences_list[[split_index]] <- data.table(
      splitID = paired$splitID,
      method_A = method_a,
      method_B = method_b,
      method_A_display = display_a,
      method_B_display = display_b,
      metric = metric,
      metric_display = metric_display,
      raw_difference_A_minus_B = raw_difference,
      favorable_difference_for_A = favorable_difference,
      test_train_ratio = paired$test_train_ratio
    )
  }
}

pairwise_results <- rbindlist(
  pairwise_results_list,
  use.names = TRUE,
  fill = TRUE
)

pairwise_results[
  ,
  p_holm_all_pairs := p.adjust(
    corrected_pvalue,
    method = "holm"
  ),
  by = metric
]

pairwise_results[
  method_A == "MGCV",
  p_holm_GAM_DMR_vs_alternatives := p.adjust(
    corrected_pvalue,
    method = "holm"
  ),
  by = metric
]

pairwise_split_differences <- rbindlist(
  pairwise_split_differences_list,
  use.names = TRUE,
  fill = TRUE
)

fwrite(
  pairwise_results,
  file.path(table_dir, "Table_S1_all_pairwise_corrected_repeated_CV.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

fwrite(
  pairwise_split_differences,
  file.path(data_dir, "pairwise_split_differences_all_methods.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

gam_vs_alternatives <- pairwise_results[
  method_A == "MGCV"
]

fwrite(
  gam_vs_alternatives,
  file.path(table_dir, "Table2_GAM_DMR_vs_alternatives_corrected_CV.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

# ---------------------- each method versus covariates ------------------------

method_vs_baseline_results_list <- list()
method_vs_baseline_split_list <- list()
result_index <- 0L
split_index <- 0L

for (method_key in method_config$method_key) {
  current_method_key <- method_key

  display_method <- method_config[
    method_key == current_method_key,
    method_display
  ][1L]

  method_perf <- primary_performance[source_method == method_key]
  baseline_perf <- baseline_performance_all[source_method == method_key]

  paired <- merge(
    method_perf,
    baseline_perf,
    by = "splitID",
    suffixes = c("_Method", "_Baseline"),
    all = FALSE
  )

  if (nrow(paired) != expected_splits) {
    stop(
      display_method,
      " versus covariates has ", nrow(paired),
      " matched splits; expected ", expected_splits, "."
    )
  }

  paired[, test_train_ratio := n_test_Method / n_train_Method]

  for (m in seq_len(nrow(comparison_metric_dictionary))) {
    metric <- comparison_metric_dictionary$metric[m]
    metric_display <- comparison_metric_dictionary$metric_display[m]
    lower_is_better <- comparison_metric_dictionary$lower_is_better[m]

    raw_difference <- paired[[paste0(metric, "_Method")]] -
      paired[[paste0(metric, "_Baseline")]]

    favorable_sign <- if (lower_is_better) -1 else 1
    improvement <- favorable_sign * raw_difference

    corrected <- corrected_repeated_cv(
      raw_difference,
      paired$test_train_ratio
    )

    corrected[, `:=`(
      source_method = method_key,
      method_display = display_method,
      comparison = paste0(display_method, " minus Covariates only"),
      metric = metric,
      metric_display = metric_display,
      lower_is_better = lower_is_better,
      favorable_sign = favorable_sign,
      favorable_mean_improvement = favorable_sign * mean_difference,
      favorable_CI_low = if (favorable_sign == 1) {
        corrected_CI_low
      } else {
        -corrected_CI_high
      },
      favorable_CI_high = if (favorable_sign == 1) {
        corrected_CI_high
      } else {
        -corrected_CI_low
      },
      improvement_win_rate = mean(improvement > 0, na.rm = TRUE),
      tie_rate = mean(improvement == 0, na.rm = TRUE)
    )]

    result_index <- result_index + 1L
    method_vs_baseline_results_list[[result_index]] <- corrected

    split_index <- split_index + 1L
    method_vs_baseline_split_list[[split_index]] <- data.table(
      splitID = paired$splitID,
      source_method = method_key,
      method_display = display_method,
      metric = metric,
      metric_display = metric_display,
      raw_difference_method_minus_baseline = raw_difference,
      favorable_improvement = improvement,
      test_train_ratio = paired$test_train_ratio
    )
  }
}

method_vs_baseline_results <- rbindlist(
  method_vs_baseline_results_list,
  use.names = TRUE,
  fill = TRUE
)

method_vs_baseline_results[
  ,
  p_holm_across_methods := p.adjust(
    corrected_pvalue,
    method = "holm"
  ),
  by = metric
]

method_vs_baseline_split <- rbindlist(
  method_vs_baseline_split_list,
  use.names = TRUE,
  fill = TRUE
)

fwrite(
  method_vs_baseline_results,
  file.path(table_dir, "Table_S2_methods_vs_covariates_corrected_CV.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

fwrite(
  method_vs_baseline_split,
  file.path(data_dir, "split_improvement_vs_covariates.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

# ------------------- subject-averaged out-of-fold predictions ----------------

primary_test_predictions <- prediction_all[
  model == primary_model_expected & prediction_set == "test"
]

primary_subject_average <- primary_test_predictions[
  ,
  .(
    AA_only = unique(AA_only)[1L],
    mean_pred_prob = mean(pred_prob, na.rm = TRUE),
    median_pred_prob = median(pred_prob, na.rm = TRUE),
    SD_pred_prob = stats::sd(pred_prob, na.rm = TRUE),
    n_test_appearances = .N
  ),
  by = .(
    source_method,
    method_display,
    ID,
    FID
  )
]

baseline_subject_average <- reference_baseline_prediction[
  ,
  .(
    AA_only = unique(AA_only_reference)[1L],
    mean_pred_prob = mean(pred_prob_reference, na.rm = TRUE),
    median_pred_prob = median(pred_prob_reference, na.rm = TRUE),
    SD_pred_prob = stats::sd(pred_prob_reference, na.rm = TRUE),
    n_test_appearances = .N
  ),
  by = .(
    ID,
    FID
  )
]

baseline_subject_average[, `:=`(
  source_method = "Covariate_only",
  method_display = "Covariates only"
)]

subject_average <- rbindlist(
  list(primary_subject_average, baseline_subject_average),
  use.names = TRUE,
  fill = TRUE
)

subject_average[, method_display := factor(
  method_display,
  levels = method_levels
)]
setorder(subject_average, method_display, ID)

subject_outcome_qc <- subject_average[
  ,
  .(
    n_unique_outcomes = uniqueN(AA_only)
  ),
  by = .(
    ID,
    FID
  )
]

if (any(subject_outcome_qc$n_unique_outcomes != 1L)) {
  stop("At least one subject has inconsistent outcomes across methods.")
}

fwrite(
  subject_average,
  file.path(data_dir, "subject_average_test_predictions_all_methods.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

subject_average_performance <- subject_average[
  ,
  probability_metrics(
    y = AA_only,
    p = mean_pred_prob
  ),
  by = .(
    source_method,
    method_display
  )
]

subject_average_performance[, method_order := match(
  as.character(method_display),
  method_levels
)]
setorder(subject_average_performance, method_order)
subject_average_performance[, method_order := NULL]

fwrite(
  subject_average_performance,
  file.path(table_dir, "Table_S4_subject_average_performance.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

# ------------------------- ROC and PR curve coordinates ----------------------

roc_coordinates_list <- list()
pr_coordinates_list <- list()

for (method_name in method_levels) {
  dd <- subject_average[
    as.character(method_display) == method_name
  ]

  if (nrow(dd) == 0L || uniqueN(dd$AA_only) < 2L) next

  roc_obj <- pROC::roc(
    dd$AA_only,
    dd$mean_pred_prob,
    levels = c(0, 1),
    direction = "<",
    quiet = TRUE
  )

  roc_coordinates_list[[method_name]] <- data.table(
    method_display = method_name,
    FPR = 1 - roc_obj$specificities,
    TPR = roc_obj$sensitivities,
    AUROC = as.numeric(pROC::auc(roc_obj))
  )

  pr_obj <- PRROC::pr.curve(
    scores.class0 = dd[AA_only == 1L, mean_pred_prob],
    scores.class1 = dd[AA_only == 0L, mean_pred_prob],
    curve = TRUE
  )

  pr_coordinates_list[[method_name]] <- data.table(
    method_display = method_name,
    Recall = pr_obj$curve[, 1L],
    Precision = pr_obj$curve[, 2L],
    PR_AUC = as.numeric(pr_obj$auc.integral),
    prevalence = mean(dd$AA_only)
  )
}

roc_coordinates <- rbindlist(
  roc_coordinates_list,
  use.names = TRUE,
  fill = TRUE
)

pr_coordinates <- rbindlist(
  pr_coordinates_list,
  use.names = TRUE,
  fill = TRUE
)

fwrite(
  roc_coordinates,
  file.path(data_dir, "subject_average_ROC_coordinates.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

fwrite(
  pr_coordinates,
  file.path(data_dir, "subject_average_PR_coordinates.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

# ---------------------------- calibration bins -------------------------------

calibration_bins <- subject_average[
  ,
  {
    n_local <- .N
    rank_local <- frank(
      mean_pred_prob,
      ties.method = "average",
      na.last = "keep"
    )

    bin_local <- pmin(
      n_calibration_bins,
      pmax(
        1L,
        ceiling(rank_local / n_local * n_calibration_bins)
      )
    )

    .(
      calibration_bin = bin_local,
      AA_only = AA_only,
      mean_pred_prob = mean_pred_prob
    )
  },
  by = .(
    source_method,
    method_display
  )
][
  ,
  .(
    n = .N,
    mean_predicted = mean(mean_pred_prob, na.rm = TRUE),
    observed = mean(AA_only, na.rm = TRUE),
    observed_SE = sqrt(
      mean(AA_only, na.rm = TRUE) *
        (1 - mean(AA_only, na.rm = TRUE)) /
        .N
    )
  ),
  by = .(
    source_method,
    method_display,
    calibration_bin
  )
]

calibration_bins[, `:=`(
  observed_CI_low = pmax(0, observed - 1.96 * observed_SE),
  observed_CI_high = pmin(1, observed + 1.96 * observed_SE)
)]

fwrite(
  calibration_bins,
  file.path(data_dir, "subject_average_calibration_bins.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

# ---------------------- region/feature selection stability -------------------

primary_coefficients <- coefficient_all[
  model == primary_model_expected &
    feature_type == "methylation" &
    grepl("^DMRpc[0-9]+_", feature)
]

primary_coefficients[, region_key := sub(
  "^DMRpc[0-9]+_",
  "",
  feature
)]

# DMRcate and BSmooth identifiers end in an artificial within-split index.
# Remove it so exact genomic intervals can be compared across splits.
primary_coefficients[
  source_method %in% c("DMRcate", "BSmooth"),
  region_key := sub("_[0-9]{5}$", "", region_key)
]

region_split_selection <- primary_coefficients[
  ,
  .(
    region_available = 1L,
    region_selected = as.integer(any(selected_nonzero == 1L)),
    n_PC_features_available = .N,
    n_PC_features_selected = sum(selected_nonzero == 1L, na.rm = TRUE),
    maximum_abs_coefficient = max(abs(coefficient), na.rm = TRUE)
  ),
  by = .(
    source_method,
    method_display,
    splitID,
    region_key
  )
]

region_stability <- region_split_selection[
  ,
  .(
    n_splits_available = uniqueN(splitID),
    n_splits_selected = sum(region_selected),
    overall_selection_rate = sum(region_selected) / expected_splits,
    conditional_selection_rate = sum(region_selected) / uniqueN(splitID),
    mean_selected_PC_count = mean(n_PC_features_selected),
    mean_maximum_abs_coefficient = mean(
      maximum_abs_coefficient,
      na.rm = TRUE
    )
  ),
  by = .(
    source_method,
    method_display,
    region_key
  )
]

setorder(
  region_stability,
  source_method,
  -n_splits_selected,
  -n_splits_available,
  region_key
)

fwrite(
  region_stability,
  file.path(table_dir, "Table_S5_region_selection_stability.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

region_stability_top <- region_stability[
  ,
  head(.SD, top_regions_per_method),
  by = .(
    source_method,
    method_display
  )
]

fwrite(
  region_stability_top,
  file.path(table_dir, "Table_S5_top_region_selection_stability.tsv"),
  sep = "\t",
  quote = FALSE,
  na = "NA"
)

# --------------------------------- figures -----------------------------------

# Figure 1: distributions of key test-set metrics.
figure1_metrics <- data.table(
  metric = c("AUROC_test", "PR_AUC_test", "Brier_test"),
  metric_display = c("AUROC", "PR-AUC", "Brier score")
)

figure1_data <- melt(
  performance_for_summary,
  id.vars = c("splitID", "method_display"),
  measure.vars = figure1_metrics$metric,
  variable.name = "metric",
  value.name = "value",
  variable.factor = FALSE
)

figure1_data <- merge(
  figure1_data,
  figure1_metrics,
  by = "metric",
  all.x = TRUE,
  sort = FALSE
)
figure1_data[, method_display := factor(
  method_display,
  levels = method_levels
)]
figure1_data[, metric_display := factor(
  metric_display,
  levels = figure1_metrics$metric_display
)]

p_figure1 <- ggplot(
  figure1_data,
  aes(x = method_display, y = value, fill = method_display)
) +
  geom_violin(trim = FALSE, alpha = 0.28, linewidth = 0.35) +
  geom_boxplot(
    width = 0.18,
    outlier.shape = NA,
    alpha = 0.75,
    linewidth = 0.35
  ) +
  geom_jitter(
    aes(color = method_display),
    width = 0.08,
    height = 0,
    size = 0.65,
    alpha = 0.35,
    show.legend = FALSE
  ) +
  stat_summary(
    fun = mean,
    geom = "point",
    shape = 23,
    size = 2.2,
    fill = "white",
    color = "black"
  ) +
  facet_wrap(~ metric_display, scales = "free_y", nrow = 1) +
  scale_fill_manual(values = method_palette, drop = FALSE) +
  scale_color_manual(values = method_palette, drop = FALSE) +
  labs(
    title = "Predictive performance across repeated family-aware test splits",
    x = NULL,
    y = NULL,
    fill = "Model"
  ) +
  base_theme +
  theme(
    axis.text.x = element_text(angle = 30, hjust = 1),
    legend.position = "none"
  )

save_plot(
  p_figure1,
  "Figure1_split_performance_distributions",
  width = 11.0,
  height = 4.4
)

# Figure 2: improvement relative to the covariate-only model. Positive values
# always indicate improvement by the regional method.
figure2_metrics <- c("AUROC", "PR-AUC", "Brier score")
figure2_data <- method_vs_baseline_split[
  metric_display %in% figure2_metrics
]
figure2_data[, method_display := factor(
  method_display,
  levels = method_levels[1:4]
)]
figure2_data[, metric_display := factor(
  metric_display,
  levels = figure2_metrics
)]

p_figure2 <- ggplot(
  figure2_data,
  aes(
    x = method_display,
    y = favorable_improvement,
    fill = method_display
  )
) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey40") +
  geom_violin(trim = FALSE, alpha = 0.30, linewidth = 0.35) +
  geom_boxplot(
    width = 0.18,
    outlier.shape = NA,
    alpha = 0.75,
    linewidth = 0.35
  ) +
  geom_jitter(
    aes(color = method_display),
    width = 0.08,
    height = 0,
    size = 0.65,
    alpha = 0.35,
    show.legend = FALSE
  ) +
  facet_wrap(~ metric_display, scales = "free_y", nrow = 1) +
  scale_fill_manual(values = method_palette, drop = FALSE) +
  scale_color_manual(values = method_palette, drop = FALSE) +
  labs(
    title = "Incremental predictive performance beyond clinical covariates",
    subtitle = "Positive values favor the regional methylation model",
    x = NULL,
    y = "Improvement relative to covariates only",
    fill = "Regional method"
  ) +
  base_theme +
  theme(
    axis.text.x = element_text(angle = 30, hjust = 1),
    legend.position = "none"
  )

save_plot(
  p_figure2,
  "Figure2_improvement_vs_covariates",
  width = 11.0,
  height = 4.6
)

# Figure 3: corrected repeated-CV differences for GAM-DMR versus alternatives.
figure3_data <- gam_vs_alternatives[
  metric_display %in% figure2_metrics
]
figure3_data[, comparator := factor(
  method_B_display,
  levels = c("SOMNiBUS", "DMRcate", "BSmooth")
)]
figure3_data[, metric_display := factor(
  metric_display,
  levels = figure2_metrics
)]

p_figure3 <- ggplot(
  figure3_data,
  aes(
    x = favorable_mean_difference,
    y = comparator,
    color = comparator
  )
) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey40") +
  geom_errorbarh(
    aes(
      xmin = favorable_CI_low,
      xmax = favorable_CI_high
    ),
    height = 0.18,
    linewidth = 0.7
  ) +
  geom_point(size = 2.6) +
  facet_wrap(~ metric_display, scales = "free_x", nrow = 1) +
  scale_color_manual(values = method_palette[c("SOMNiBUS", "DMRcate", "BSmooth")]) +
  labs(
    title = "Paired GAM-DMR performance relative to alternative regional methods",
    subtitle = "Corrected repeated-CV mean differences and 95% confidence intervals; positive values favor GAM-DMR",
    x = "Favorable difference for GAM-DMR",
    y = NULL,
    color = "Comparator"
  ) +
  base_theme +
  theme(legend.position = "none")

save_plot(
  p_figure3,
  "Figure3_GAM_DMR_pairwise_forest",
  width = 10.6,
  height = 4.1
)

# Figure 4A: subject-averaged ROC curves.
roc_coordinates[, method_display := factor(
  method_display,
  levels = method_levels
)]
roc_labels <- unique(
  roc_coordinates[
    ,
    .(
      method_display,
      AUROC
    )
  ]
)
roc_labels[, curve_label := paste0(
  as.character(method_display),
  " (AUROC=",
  format_number(AUROC, 3L),
  ")"
)]
roc_coordinates <- merge(
  roc_coordinates,
  roc_labels,
  by = c("method_display", "AUROC"),
  all.x = TRUE,
  sort = FALSE
)

roc_label_palette <- setNames(
  method_palette[as.character(roc_labels$method_display)],
  roc_labels$curve_label
)

p_roc <- ggplot(
  roc_coordinates,
  aes(x = FPR, y = TPR, color = curve_label)
) +
  geom_line(linewidth = 1.05) +
  geom_abline(linetype = "dashed", color = "grey50") +
  coord_equal() +
  scale_color_manual(values = roc_label_palette) +
  labs(
    title = "Subject-averaged out-of-fold ROC curves",
    x = "False-positive rate",
    y = "True-positive rate",
    color = "Model"
  ) +
  base_theme

save_plot(
  p_roc,
  "Figure4A_subject_average_ROC",
  width = 7.5,
  height = 6.3
)

# Figure 4B: subject-averaged precision-recall curves.
pr_coordinates[, method_display := factor(
  method_display,
  levels = method_levels
)]
pr_labels <- unique(
  pr_coordinates[
    ,
    .(
      method_display,
      PR_AUC
    )
  ]
)
pr_labels[, curve_label := paste0(
  as.character(method_display),
  " (PR-AUC=",
  format_number(PR_AUC, 3L),
  ")"
)]
pr_coordinates <- merge(
  pr_coordinates,
  pr_labels,
  by = c("method_display", "PR_AUC"),
  all.x = TRUE,
  sort = FALSE
)

pr_label_palette <- setNames(
  method_palette[as.character(pr_labels$method_display)],
  pr_labels$curve_label
)

prevalence_line <- subject_average[
  as.character(method_display) == "Covariates only",
  mean(AA_only)
]

p_pr <- ggplot(
  pr_coordinates,
  aes(x = Recall, y = Precision, color = curve_label)
) +
  geom_line(linewidth = 1.05) +
  geom_hline(
    yintercept = prevalence_line,
    linetype = "dashed",
    color = "grey50"
  ) +
  scale_color_manual(values = pr_label_palette) +
  labs(
    title = "Subject-averaged out-of-fold precision-recall curves",
    subtitle = paste0(
      "Dashed line: outcome prevalence = ",
      format_number(prevalence_line, 3L)
    ),
    x = "Recall",
    y = "Precision",
    color = "Model"
  ) +
  base_theme

save_plot(
  p_pr,
  "Figure4B_subject_average_PR",
  width = 7.5,
  height = 6.3
)

# Figure 5: calibration plot.
calibration_bins[, method_display := factor(
  method_display,
  levels = method_levels
)]

p_calibration <- ggplot(
  calibration_bins,
  aes(
    x = mean_predicted,
    y = observed,
    color = method_display,
    group = method_display
  )
) +
  geom_abline(linetype = "dashed", color = "grey50") +
  geom_errorbar(
    aes(
      ymin = observed_CI_low,
      ymax = observed_CI_high
    ),
    width = 0.012,
    alpha = 0.45,
    linewidth = 0.45
  ) +
  geom_line(linewidth = 0.85) +
  geom_point(size = 1.9) +
  coord_equal(xlim = c(0, 1), ylim = c(0, 1)) +
  scale_color_manual(values = method_palette, drop = FALSE) +
  labs(
    title = "Calibration of subject-averaged out-of-fold predictions",
    x = "Mean predicted probability",
    y = "Observed AA proportion",
    color = "Model"
  ) +
  base_theme

save_plot(
  p_calibration,
  "Figure5_subject_average_calibration",
  width = 7.2,
  height = 6.3
)

# Supplementary Figure 1: model complexity.
complexity_plot_data <- complexity_long[
  metric %in% c(
    "n_DMR_selected_input",
    "n_DMR_usable",
    "n_methylation_features_nonzero"
  )
]
complexity_plot_data[, method_display := factor(
  method_display,
  levels = method_levels[1:4]
)]
complexity_plot_data[, metric_display := factor(
  metric_display,
  levels = c(
    "Selected DMRs",
    "Usable DMRs",
    "Nonzero methylation PC features"
  )
)]

p_complexity <- ggplot(
  complexity_plot_data,
  aes(x = method_display, y = value, fill = method_display)
) +
  geom_violin(trim = FALSE, alpha = 0.30, linewidth = 0.35) +
  geom_boxplot(
    width = 0.18,
    outlier.shape = NA,
    alpha = 0.75,
    linewidth = 0.35
  ) +
  geom_jitter(
    aes(color = method_display),
    width = 0.08,
    size = 0.65,
    alpha = 0.30,
    show.legend = FALSE
  ) +
  facet_wrap(~ metric_display, scales = "free_y", nrow = 1) +
  scale_fill_manual(values = method_palette, drop = FALSE) +
  scale_color_manual(values = method_palette, drop = FALSE) +
  labs(
    title = "Regional feature-set complexity across outer splits",
    x = NULL,
    y = "Count",
    fill = "Regional method"
  ) +
  base_theme +
  theme(
    axis.text.x = element_text(angle = 30, hjust = 1),
    legend.position = "none"
  )

save_plot(
  p_complexity,
  "Figure_S1_model_complexity",
  width = 11.0,
  height = 4.5
)

# Supplementary Figure 2: predictive performance versus selected DMR count.
performance_count_data <- rbindlist(
  list(
    primary_performance[
      ,
      .(
        splitID,
        method_display,
        selected_DMRs = n_DMR_selected_input,
        metric_display = "AUROC",
        performance = AUROC_test
      )
    ],
    primary_performance[
      ,
      .(
        splitID,
        method_display,
        selected_DMRs = n_DMR_selected_input,
        metric_display = "PR-AUC",
        performance = PR_AUC_test
      )
    ]
  ),
  use.names = TRUE
)
performance_count_data[, method_display := factor(
  method_display,
  levels = method_levels[1:4]
)]

p_count_performance <- ggplot(
  performance_count_data,
  aes(
    x = selected_DMRs,
    y = performance,
    color = method_display
  )
) +
  geom_point(size = 1.1, alpha = 0.45) +
  geom_smooth(method = "lm", se = TRUE, linewidth = 0.8) +
  facet_wrap(~ metric_display, scales = "free", nrow = 1) +
  scale_color_manual(values = method_palette, drop = FALSE) +
  labs(
    title = "Test performance versus the number of selected DMRs",
    x = "Selected DMRs in the outer training split",
    y = "Test performance",
    color = "Regional method"
  ) +
  base_theme

save_plot(
  p_count_performance,
  "Figure_S2_performance_vs_selected_DMR_count",
  width = 10.0,
  height = 4.8
)

# Supplementary Figure 3: most frequently retained regional predictors.
region_stability_top[, method_display := factor(
  method_display,
  levels = method_levels[1:4]
)]
region_stability_top[, region_label := factor(
  region_key,
  levels = rev(unique(region_key))
)]

p_region_stability <- ggplot(
  region_stability_top,
  aes(
    x = n_splits_selected,
    y = reorder(region_key, n_splits_selected),
    fill = method_display
  )
) +
  geom_col(width = 0.75) +
  facet_wrap(
    ~ method_display,
    scales = "free_y",
    ncol = 2
  ) +
  scale_fill_manual(values = method_palette, drop = FALSE) +
  labs(
    title = "Most frequently retained regional methylation predictors",
    subtitle = "A region is counted when at least one of its PC features has a nonzero LASSO coefficient",
    x = "Number of outer splits with a nonzero regional coefficient",
    y = "Region identifier"
  ) +
  base_theme +
  theme(
    legend.position = "none",
    axis.text.y = element_text(size = 7)
  )

save_plot(
  p_region_stability,
  "Figure_S3_region_selection_stability",
  width = 10.0,
  height = 8.0
)

# ----------------------- manuscript text and captions ------------------------

mean_metric_table <- performance_summary_numeric[
  metric %in% c("AUROC_test", "PR_AUC_test", "Brier_test") &
    as.character(method_display) != "Covariates only",
  .(
    method_display = as.character(method_display),
    metric,
    mean,
    SD,
    median,
    Q1,
    Q3
  )
]

best_auc <- mean_metric_table[
  metric == "AUROC_test"
][order(-mean)][1L]

best_pr <- mean_metric_table[
  metric == "PR_AUC_test"
][order(-mean)][1L]

best_brier <- mean_metric_table[
  metric == "Brier_test"
][order(mean)][1L]

results_text <- c(
  "PRIMARY REGIONAL-METHOD PREDICTION COMPARISON",
  "",
  paste0(
    "Across ", expected_splits,
    " repeated family-aware outer train/test splits, the highest mean test AUROC was observed for ",
    best_auc$method_display,
    " (mean ", format_number(best_auc$mean, 3L),
    ", SD ", format_number(best_auc$SD, 3L), ")."
  ),
  paste0(
    "The highest mean test PR-AUC was observed for ",
    best_pr$method_display,
    " (mean ", format_number(best_pr$mean, 3L),
    ", SD ", format_number(best_pr$SD, 3L), ")."
  ),
  paste0(
    "The lowest mean Brier score was observed for ",
    best_brier$method_display,
    " (mean ", format_number(best_brier$mean, 3L),
    ", SD ", format_number(best_brier$SD, 3L), ")."
  ),
  "",
  "GAM-DMR VERSUS ALTERNATIVE REGIONAL METHODS",
  ""
)

for (metric_name in c("AUROC", "PR-AUC", "Brier score")) {
  dd <- gam_vs_alternatives[metric_display == metric_name]

  for (i in seq_len(nrow(dd))) {
    direction_text <- if (dd$favorable_mean_difference[i] > 0) {
      "favored GAM-DMR"
    } else if (dd$favorable_mean_difference[i] < 0) {
      paste0("favored ", dd$method_B_display[i])
    } else {
      "showed no average difference"
    }

    results_text <- c(
      results_text,
      paste0(
        metric_name,
        ": GAM-DMR versus ", dd$method_B_display[i],
        " had a favorable-direction mean difference of ",
        format_number(dd$favorable_mean_difference[i], 3L),
        " (corrected 95% CI ",
        format_number(dd$favorable_CI_low[i], 3L),
        " to ",
        format_number(dd$favorable_CI_high[i], 3L),
        "; Holm-adjusted p ",
        format_pvalue(dd$p_holm_GAM_DMR_vs_alternatives[i]),
        "), which ", direction_text, "."
      )
    )
  }

  results_text <- c(results_text, "")
}

results_text <- c(
  results_text,
  "Interpretation note: for AUROC and PR-AUC, positive favorable-direction differences mean higher performance for GAM-DMR. For Brier score, positive favorable-direction differences mean a lower Brier score for GAM-DMR.",
  "Corrected repeated-CV confidence intervals account approximately for overlap among the repeated 80/20 splits. The subject-averaged ROC, PR, and calibration analyses are secondary descriptive ensemble summaries.",
  ""
)

writeLines(
  results_text,
  con = file.path(output_root, "manuscript_results_summary.txt")
)

caption_text <- c(
  "Figure 1. Predictive performance across repeated family-aware outer test splits. Violin and box plots show the distributions of test-set AUROC, PR-AUC, and Brier score across the repeated splits. White diamonds indicate arithmetic means. All regional models used split-specific training-derived DMRs, training-only PC construction, family-grouped inner cross-validation, and an outer held-out family test set.",
  "",
  "Figure 2. Incremental predictive performance beyond clinical covariates. Values represent the paired split-specific improvement of each regional methylation model over the covariate-only model. Positive values indicate improvement; Brier-score differences were sign-reversed so that positive values consistently indicate better performance.",
  "",
  "Figure 3. Paired comparison of GAM-DMR with alternative regional methods. Points show corrected repeated-CV mean differences and horizontal bars show corrected 95% confidence intervals. Effects are oriented so that positive values favor GAM-DMR; Brier-score differences were sign-reversed.",
  "",
  "Figure 4A. Subject-averaged out-of-fold ROC curves. For each participant and method, predicted probabilities were averaged across all outer splits in which that participant was held out. This is a secondary descriptive ensemble analysis.",
  "",
  "Figure 4B. Subject-averaged out-of-fold precision-recall curves. The dashed horizontal line shows the observed AA prevalence. This is a secondary descriptive ensemble analysis.",
  "",
  "Figure 5. Calibration of subject-averaged out-of-fold predictions. Points show observed AA proportions within prediction-ranked bins; error bars show approximate 95% binomial confidence intervals. The dashed diagonal represents perfect calibration.",
  "",
  "Supplementary Figure 1. Regional feature-set complexity across outer splits, including selected DMR counts, usable DMR counts, and nonzero methylation PC features.",
  "",
  "Supplementary Figure 2. Relationship between the number of selected training-derived DMRs and held-out test performance.",
  "",
  "Supplementary Figure 3. Most frequently retained regional methylation predictors. A region is counted as retained when at least one PC feature from that region has a nonzero LASSO coefficient in an outer split."
)

writeLines(
  caption_text,
  con = file.path(output_root, "manuscript_figure_captions.txt")
)

readme_text <- c(
  "REGIONAL METHOD COMPARISON OUTPUTS",
  "",
  "Recommended main-manuscript outputs:",
  "  tables/Table1_primary_performance_formatted.tsv",
  "  tables/Table2_GAM_DMR_vs_alternatives_corrected_CV.tsv",
  "  figures/Figure1_split_performance_distributions.pdf",
  "  figures/Figure2_improvement_vs_covariates.pdf",
  "  figures/Figure3_GAM_DMR_pairwise_forest.pdf",
  "  figures/Figure4A_subject_average_ROC.pdf",
  "  figures/Figure4B_subject_average_PR.pdf",
  "  figures/Figure5_subject_average_calibration.pdf",
  "",
  "Recommended supplementary outputs:",
  "  tables/Table_S1_all_pairwise_corrected_repeated_CV.tsv",
  "  tables/Table_S2_methods_vs_covariates_corrected_CV.tsv",
  "  tables/Table_S3_model_complexity_formatted.tsv",
  "  tables/Table_S4_subject_average_performance.tsv",
  "  tables/Table_S5_region_selection_stability.tsv",
  "  figures/Figure_S1_model_complexity.pdf",
  "  figures/Figure_S2_performance_vs_selected_DMR_count.pdf",
  "  figures/Figure_S3_region_selection_stability.pdf",
  "",
  "Statistical note:",
  "  Descriptive summaries report distributions across repeated splits.",
  "  Pairwise inference uses the corrected repeated-CV standard error based",
  "  on the paired split-specific metric differences and the average outer",
  "  test-to-training sample-size ratio. Holm adjustment is supplied within",
  "  each metric family.",
  "",
  "Curve note:",
  "  Subject-averaged ROC, PR, and calibration results are secondary",
  "  descriptive ensemble summaries rather than performance estimates from",
  "  one single fitted model."
)

writeLines(
  readme_text,
  con = file.path(output_root, "README_outputs.txt")
)

capture.output(
  sessionInfo(),
  file = file.path(output_root, "R_sessionInfo.txt")
)

# -------------------------------- final log -----------------------------------

cat("\nRegional-method comparison completed.\n")
cat("Output root:", output_root, "\n")
cat("Tables:", table_dir, "\n")
cat("Figures:", figure_dir, "\n")
cat("Analysis datasets:", data_dir, "\n")
cat("QC:", qc_dir, "\n")
cat("Primary performance rows:", nrow(primary_performance), "\n")
cat("Subject-average prediction rows:", nrow(subject_average), "\n")
cat("Pairwise corrected comparisons:", nrow(pairwise_results), "\n")
cat("Method-versus-covariate comparisons:", nrow(method_vs_baseline_results), "\n")

print(
  performance_summary_numeric[
    metric %in% c("AUROC_test", "PR_AUC_test", "Brier_test"),
    .(
      Method = as.character(method_display),
      Metric = metric_display,
      Mean = mean,
      SD = SD,
      Median = median,
      Q1 = Q1,
      Q3 = Q3
    )
  ]
)
